on:
  push:
    branches:    
      - main
name: Test Suite
jobs:
  iOS:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        version: [macOS]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/cache@v2
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
                ${{ runner.os }}-carthage-

      - name: Carthage
        if: steps.carthage-cache.outputs.cache-hit != 'true'
        run: |
          carthage bootstrap --no-use-binaries --platform $platform --cache-builds
          rm -rf ./Carthage/Build/$platform/*.dSYM

      - name: Build
        run: |
          export ABLY_ENV="sandbox"
          xcodebuild -scheme Ably-macOS-Tests -project ./Ably.xcodeproj ABLY_ENV=sandbox clean build test
    env:
      target: ably-macOS
      platform: Mac
      lane: test_${{ matrix.version }}
